### ISSUE TITLE
REWORK: Diversify Armor types light/medium/heavy

### ISSUE THREAD

**Issue by Sasabmeg** [Sasabmeg/FOnline-BraveNewWorld#17]
Latest update for design:

- **Heavy Armor**: Metal/Tesla (also Power armor but hat is unique)
  - _Negatives_:
    - 0% AP regen while running, 50% reduced AP regen while walking (this is reduction on reduction, so prob end up somewhere 25%%)
    - -2 AG because of clumsiness
    - (need to decide fi we put -AP here or not? prob not AP regen is enough penalty)
    - heavy weight as before
    - not possible to sneak in (maybe with stealth boy?)
  - _Positives_:
    - Highest DT/DR
    - Stonewall Perk free (maybe if character has stonewall too, its a bit stronger)
- **Medium Armor**: (Combat armor types)
  - _Negatives_:
    - 50% AP regen while running, 75% while walking (for example human skin gets 50% run AP regen naked, this would be 25% in combat armor)
    - not possible to sneak in ? or big sneak penalty (maybe with stealth boy)
    - medium DT/DR
  - _Positives_:
     - Bonus Perk: iron Limbs (because armor looks like protecting hands and legs, while heavy armor doesn't)
- **Light Armor**: (Leather Jacket, Armor, Thermal armor or other stuff like that, idk about robes?)
  - _Negatives_:
    - Lowest DT/DR 
  - _Positives_:
     - No extra AP regen reductions besides what skin gives
     - +1 Charisma for Jacket, +1 AG for LEather Armors
     - Sneak Bonus compared to Bluesuit (dark armors harder to see, no noise like metal or combat)
     - Other variants may have bonus perks like: Quick Draw, Reload, Pockets, whatever, Quick Recovery? (getting up from Knockdown bc armor is light)

+ Rado added some walk/run speed to armors, that could be used too.

--------------------------

As described in the BNW concepts discussion, armor types should change from Single Player like vertical advancement, to more variety in use, build etc. There should three basic types of armor, Leather (or light) Armor, Combat (or medium) Armor and Metal (or heavy) Armor.
- Light Armor (Leather Armors): Low Protections, +1 AP, +2 AG, +50 Sneak, +Quick Pockets Perk, +Quick Draw Perk (later because needs more work, add animation between standing still and shooting, that should be faster on factor of 1.5)
- Medium Armor (Combat Armors): Medium Protections, -2 AG, -30 Sneak, +Iron Limbs Perk
- Heavy Armor (Metal Armor/Tesla): High Protections, -2 AP, -2 AG, -50 Sneak,  +Stonewall Perk

Power Armor and Enclave Armor shall have no drawback, +Stonewall Perk, +Iron Limbs Perk, +2 ST, or other of the usual benefits, but very rare.

In addition, the armor type worn would limit the players ability to run fast, similar to solutions where running speed is increased when melee/unarmed weapon equipped, this could be affected by armor type as well in small amounts.

**Comment by LinuxFO** [comment]
I understand it is only random suggestion, sketch or something like that but I dont like the provided stats/changes especially for Heavy Armor: imo 3 big drawbacks ( -2 AP, -2 AG, -50 Sneak) vs 1 small positive (+Stonewall Perk) compared to how important APs and AG are.

TBH changin armors or weapons are always hard way to do it good and balanced way.

**Comment by Sasabmeg** [comment]
Guess an explanation of the idea is required...

> I understand it is only random suggestion, sketch or something like that but I dont like the provided stats/changes especially for Heavy Armor: imo 3 big drawbacks ( -2 AP, -2 AG, -50 Sneak) vs 1 small positive (+Stonewall Perk) compared to how important APs and AG are.

Heavy Armor as in current suggestion 2 positives (+1 the protection bonuses) Item weight is not an issue, but protections are a big deal imo. Let's say if Metal has  +10% DR and +3 DT compared to Combat Armor, and also those suggested 3 big drawbacks which one would you wear? Would it be always the same? Different per build? Situation? Team? Etc. Currently it's almost always Combat Armor, this is what I think it's the problem.

> TBH changing armors or weapons are always hard way to do it good and balanced way.

Magnitude of drawbacks and advantages to be refined ofc, the main idea here is to move from linear progression of armor/weapon choices to wider in variety / situation. 
The question is, if you leave Power/Tesla Armors out of the equation, how would you change Leather, Combat and Metal armors in a way that player usage would vary from about:
 - 90% players using Combat Armor and 5% of player maybe use Leather to sneak and rest use Metal because they didn't got Combat Armor yet, 
to something like:
- not more than 60% players use the very same armor, may that be Combat, Heavy or Leather?

In general this change must feel good for a new player and feel very bad/frustrating to a veteran FOnline player, due to history and getting used to no variety, but same min-max on same server. If a player has trouble deciding that might just be a sign of good design.

**Comment by Sasabmeg** [comment]
**Armor changes:**

Separated armors into categories, to break from the linear progression of armor ( `Leather < Metal < CA < PA` ) of the original single player game.
- Light Armor category:
  - Leather Armors, Jackets and Thermal Leather.
  - +1 AG for wearer.
  - Gives Quick Pocket Perk effect (does not show on interface, but cost of use is reduced) does not stack with Quick Pocket Perk if it was taken.
  - Resistances increased a bit so they are a viable choice for combat where one in not in is the middle of action or low return fire.
- Medium Armor category:
  - All Combat Armors, including Desert, NCR, Enclave and BoH.
  - -1 AG for wearer.
  - Gives Iron Limbs Perk effect (not shown on interface, but part of calculations), this does stack (boosts) with Iron Limbs if taken by player.
  - Resistances refactored to be a bit below Heavy Armor in general.
  - Uncraftable/Rare combat armors (BH, Enclave, NCR and Desert) each have a unique resistance bonus compared to the others.
- Heavy Armor category:
  - All Metal Armors, Power Armors and Tesla.
  - -3 AG for wearer.
  - Gives Stonewall Perk effect (not shown, but part of calc), this does stack (boosts) with player's Stonewall Perk if taken.
  - Resistances refactored to have the highest resistances, but having some weakness to Electric and Fire in case of Metal Armors.

**Action Points regen while moving:**

Depending on armor type, players (maybe later NPC's) will be able to regenerate AP while running or walking at a different ratio.
- Base AP regen while standing still is 4 second for full AP, as before, this is 100% AP regen.
- Bluesuit: 50% walking, 25% running.
- Light Armor: 40% walking, 20% running.
- Medium Armor: 30% walking, 15% running.
- Heavy Armor: 20% walking, 10% running.
-
