### ISSUE TITLE
Create a tutorial module that explain controls

### ISSUE THREAD

**Issue by Sasabmeg** [Sasabmeg/FOnline-BraveNewWorld#55]
The tutorial camp is only good to engage in game mechanics like crafting and moving around doing random quests.

However there are a lot of controls, that are not intuitive, like keyboard shortcuts.
There should be a tutorial that pops, only once, when player encounters new features or is about to encounter them.
This should be if possible in AS, maybe a pop-up once, that can pop images, or play voice explanation.

**Comment by LinuxFO** [comment]
I would love to see a list of all possible keyboard shortcuts. I remember few or even more are hidden in ini files to edit. Also F1 screen in game could be updated.

**Comment by Sasabmeg** [comment]
F1 screen has been updated and this issue became a duplicated, there is another with better description see #121
