### ISSUE TITLE
Cooldowns over max possible duration after server restart/world safe wipe, etc.

### ISSUE THREAD

**Issue by Sasabmeg** [Sasabmeg/FOnline-BraveNewWorld#61]
Seems like most server have this issue, I think the root cause is that player data is saved separately from the world, thus the world timer sets back, while player CD time would be still in the far future.

Maybe once a player logs in, their CD must be checked and corrected to max possible if more than that.

**Comment by LinuxFO** [comment]
Same as newest issue?
https://github.com/Sasabmeg/FOnline-BraveNewWorld/issues/102

**Comment by Sasabmeg** [comment]
yes, double post is what I get for ignoring an issue for a year... commit fix to any of these, I will close both when finished
